import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// app/layout.js
import 'bootstrap/dist/css/bootstrap.min.css';

import ReduxProvider from "./providers/ReduxProvider";

import { Toaster } from "react-hot-toast";

import { QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "./providers/ReactQueryProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-center"></Toaster>

        <ReduxProvider>
          <ReactQueryProvider>
            
            {children}

          </ReactQueryProvider>

        </ReduxProvider>

      </body>
    </html>
  );
}


